### PR TITLE
Introduces MbArrays

### PR DESCRIPTION
**Pull request by Roldak**
Finally :D

### CODE REVIEW

**Comment by VladUreche** [comment]
Woooohoooo!

**Comment by VladUreche** [comment]
Thanks @Roldak, looks very good!

**Comment by VladUreche** [comment]
Published: http://scala-miniboxing.org/arrays.html

**Comment by VladUreche** [comment]
@Roldak, do you have the file somewhere? I would like to link to it in the tutorial.

**Comment by Roldak** [comment]
Which file are you talking about ? If you mean the mergesort, it's here https://github.com/Roldak/mb-benchmarks/blob/master/mergesort-mb/src/main/scala/Main.scala for the mb version and https://github.com/Roldak/mb-benchmarks/blob/master/mergesort-comp-no-mb/src/main/scala/Main.scala for the non mb version. But there is already a (not very visible) link to the repo at the end of the tutorial

**Comment by VladUreche** [comment]
What I had in mind is that we omit the mergesort code itself, since it doesn't change at all and instead link to the file on github -- so the person reading the tutorial can focus on the important changes -- `Array => MbArray` etc. WDYT?

How I see it:

> Blah blah blah yada yada mergesort code (full version of this code [is available on github](https://github.com/Roldak/mb-benchmarks/blob/master/mergesort-mb/src/main/scala/Main.scala)):
> 
> ```
>   def mergeSort[T : ClassTag](ary: Array[T], comp: (T, T) => Boolean): Array[T] = {
>     def merge(a: Array[T], b: Array[T]): Array[T] = {
>       val res = new Array[T](a.length + b.length)
>       ...
>     }
>     val len = ary.length
>     if (len <= 1) ary
>     else {
>       val mid = len / 2
>       val a = new Array[T](mid)
>       val b = new Array[T](len - mid)  
>       ...   
>       merge(mergeSort(a, comp), mergeSort(b, comp))
>     }
>   }
> ```

This is much easier to follow (assuming you know mergesort) and it's easier to focus on the changes, namely the `@miniboxed` annotation and the `MbArray`s.

**Comment by VladUreche** [comment]
By the way, I suggest another sequence of events for the page:
- start from adding the miniboxing plugin, which will let you know you should mark `mergeSort`'s type parameter `T` as `@miniboxed`
- mark `T` as `@miniboxed` and recompile
- now the miniboxing plugin should tell you the `Array`s can be replaced by `MbArray`s
- update `Array`s to `MbArray`s, and remove the `ClassTag`
- re-benchmark the example. 

Whoot, it's also faster! :) Btw, you should also include the hand-specialized example.

**Comment by Roldak** [comment]
Okay I'll try to do it this evening !

**Comment by VladUreche** [comment]
Thanks Romain!

**Comment by Roldak** [comment]
Mhh it seems like I don't get any warnings telling me I should use MbArray instead of Array of T in this case : 

```
def mergeSortCT[@miniboxed T: ClassTag](ary: Array[T], comp: (T, T) => Boolean): Array[T] = {
    def merge(a: Array[T], b: Array[T]): Array[T] = {
      val res = new Array[T](a.length + b.length)
      ...
```

Is this to be expected ?

**Comment by VladUreche** [comment]
Yes. Must be another error. Can you please minimize this and file a bug for the miniboxing plugin?

**Comment by Roldak** [comment]
[Done](https://github.com/miniboxing/miniboxing-plugin/issues/214)

**Comment by VladUreche** [comment]
Thanks Romain! Let's have this fixed before we continue.

**Comment by Roldak** [comment]
In the meantime, what do you think about [this](http://roldak.github.io/arrays.html) ?

**Comment by Roldak** [comment]
Also, when you say I should include the hand-specialized example, should I simply include the numbers I got with it in the table of the benchmark section (with a link to the source code too) ?

**Comment by VladUreche** [comment]
> In the meantime, what do you think about this?

I'm amazed a Bachelor student can write so clearly! You're an expert Romain!

These are some minor points I gathered along the way, but nothing major:
- In the REPL snippets, don't separate the code and the result. For example, when creating `class A`, you can say:

> Raw arrays offer the best access performance for primitive types, but they can only be instantiated in generic contexts if a ClassTag is present – which is not always possible. For example:
> 
> ```
> scala> class A[T](len: Int) {
>      |   val array = new Array[T](len)
>      | }
> <console>:8: error: cannot find class tag for element type T
>        val array = new Array[T](len)
> ```
- `scala runtime` => `Scala runtime`
- `informations` => `information`, `performances` => `performance`, `advices => advice`
- "While this works, it may not be sufficiently fast for algorithms where high performance is expected." => you should strengthen this, for example: "While this wasn't too difficult for class B, the transformation is not possible in the general case because it affects all generics transitively: 

```
scala> class C[T] extends B[T]
<console>:16: error: No ClassTag available for T
       class C[T] extends B[T]
                          ^
```

Thus, in many applications, programmers have resorted to allocating arrays of object and casting them as generic arrays, an approach which is both incorrect and slow:

```
scala> def baz[T] = new Array[AnyRef](10).asInstanceOf[Array[T]]
baz: [T]=> Array[T]

scala> baz[Int](0)
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [I
  ... 33 elided
```
- If you would like to see the whole source code, it can be found here. => you can also point to the github repository :) 
- You should add the back quotes whenever you refer to `Array`, `MbArray`, `ClassTag` etc.
- You don't need the spaces before the colon (`REPL :` => `REPL:`) 
- `MbArrays with the Miniboxing transformation : Can be ...` => `MbArray: Can be ...` 

<br/><br/>

> Also, when you say I should include the hand-specialized example, should I simply include the numbers I got with it in the table of the benchmark section (with a link to the source code too) ? 

You can mention in a paragraph that, out of curiosity, we also tested the monomorphic code and link to it. Then you can directly put the numbers in.

**Comment by Roldak** [comment]
Thank you ! :D
Okay, I will apply your suggestions !

**Comment by Roldak** [comment]
[What do you think now](http://roldak.github.io/arrays.html) ? 

(PS : sorry for the erroneously pushing to the base repo, I'm really not well awake today)

**Comment by VladUreche** [comment]
Awesome! Here's a cool addition:
speed

**Comment by VladUreche** [comment]
I think in other benchmarks we'll get an even better speedup. In the case of sorting we're not allocating any objects => `MbArray[T]` is quite close to the performance of `Array[AnyRef]`.

Btw, it should be `Array[AnyRef]`, not `Array[Any]`.

**Comment by VladUreche** [comment]
> PS : sorry for the erroneously pushing to the base repo, I'm really not well awake today

No idea what you're talking about. But if you didn't force-push (`push -f`) it's fine.

**Comment by VladUreche** [comment]
If you want to add the graph to the page, you can download it from this URL => https://cloud.githubusercontent.com/assets/428706/7540931/b29d618e-f5b1-11e4-8bfb-f20e67fb37bf.png

**Comment by Roldak** [comment]
Oh nice ! I will surely include it !

> No idea what you're talking about. But if you didn't force-push (push -f) it's fine.

I'm talking about [this](https://github.com/miniboxing/miniboxing.github.io/commit/6ed53510eeb6d307c3abe31457aea799ebf4f440). I was editing the file on github directly and I realized too late that I wasn't editing the one of my fork. I fixed it myself with [this commit](https://github.com/miniboxing/miniboxing.github.io/commit/a3f7755b6320026c5d77f62ac80d4a161bdfbe11), but it would be better if you could erase both of them (I don't know if it's possible)

**Comment by VladUreche** [comment]
No worries, it's fine.

**Comment by Roldak** [comment]
How do find the page right now?

**Comment by VladUreche** [comment]
Honestly? Now it looks like there's no reason to choose `MBArray[T]` over `Array[AnyRef]`. Doesn't it look that way?

**Comment by Roldak** [comment]
Mh you're right. I guess we should have a benchmark in which we actually perform operations on the elements instead of simply copying them right ?

**Comment by VladUreche** [comment]
Yes, otherwise the natural conclusion is that `Array[AnyRef].asInstanceOf[Array[T]]` is good enough, save for the case where it escapes.

One such benchmark would be summing up the elements in the array (and you could use `MiniboxedNumeric[T]`) which works on the miniboxed encoding directly -- start from `Numeric[T]` and the warnings should guide you from there :). 

Btw, ping @milosstojanovic -- have you seen [the page](http://roldak.github.io/arrays.html)?

**Comment by Roldak** [comment]
Is there a page explaining what MiniboxedNumeric[T] is ?

**Comment by Roldak** [comment]
As for summing the elements of the array, don't you think it's too simple that the integers will not even get boxed ?

**Comment by VladUreche** [comment]
> Is there a page explaining what MiniboxedNumeric[T] is ?

Not yet, but we should have it :)

> As for summing the elements of the array, don't you think it's too simple that the integers will not even get boxed ?

That may be the case, yes, but at the very least, each integer will have to be unboxed individually.

**Pull request merged**
